### ISSUE TITLE
Delete saved templates

### ISSUE THREAD

**Issue by bondjimbond** [mnylc/islandora_multi_importer#114]
I can't find any way to delete saved templates. Is this possible? If not, could such a feature be added easily?

**Comment by DiegoPino** [comment]
admin/islandora/twigtemplates all is there


Will mark this one as solved

Diego Pino Navarro
Assistant Director for Digital Strategy
Metropolitan New York Library Council
599 11th Av. New York, NY 10036

**Comment by bondjimbond** [comment]
@DiegoPino Thanks! After a bit of poking around I was able to find the menu item for that under the Islandora heading.

It's a bit confusing to have one IMI config page under Islandora, and another under Islandora Utility Modules. Could we maybe have a tabbed menu so that these items are available together?

**Comment by DiegoPino** [comment]
We could, of course (need more quorum, ask ICG around so we don't change their internal docs and current users expectations, there are quite a few in the wild). The reason behind that decision was to mimic (common place) how and where Form builder was listing its XML forms. Users from the beginning thought it worked for them. Versus the other settings, which are not really associated with the twig templates but with the internal workings. In other words, grouping Twig template listing with IMI settings felt like a bad idea, first one being just a tiny chunk of the whole machinery.

**Comment by bondjimbond** [comment]
I'm not suggesting to actually move where the items are found in the Drupal menu system, but to include them as tabs, e.g. screenshot. I think it's possible to have the tab menu link in a different place than the parent?
![Screen Shot 2020-04-07 at 9 38 08 AM](https://user-images.githubusercontent.com/6069170/78675799-91ded380-78b3-11ea-82a6-4d7c0d04b230.png)

**Comment by DiegoPino** [comment]
Oh, totally! You willing to become a committer? Would merge that one in a second =) Thanks

**Comment by bondjimbond** [comment]
Heh, maybe eventually if I gain some competency with this. :)

I'm not actually sure *how* we can do the tab thing without changing the paths, now that I dig into it.
