### ISSUE TITLE
Ingest without files - Errors in batch

### ISSUE THREAD

**Issue by bondjimbond** [mnylc/islandora_multi_importer#122]
Following up on #116, I tried ingesting a batch of 83 collections, which turned out to have mixed results.

Islandora Batch returns an "Unknown error" for each one on ingest:

`Unknown error: Failed to ingested npc:aemacindo`

Yet the collections are present in the system now.

[npc_imi.csv.zip](https://github.com/mnylc/islandora_multi_importer/files/5378974/npc_imi.csv.zip)

**Comment by DiegoPino** [comment]
Hi, can you share some Drupal logs please? It may be Mr. Islandora Batch queue with same PIDs you are passing already stored in other sets.

**Comment by bondjimbond** [comment]
It didn't produce any Drupal log entries. But you may be right; the PIDs could have been present from earlier failed attempts before the module was updated. I tried with some new PIDs, and it worked without errors. Thanks.

**Comment by DiegoPino** [comment]
@bondjimbond i can check for eventual conflicts on the initial pass if that works. Feel free to open a ticket for that if this (Batch queue SQL schema) is just too annoying. Thanks
