### ISSUE TITLE
Can we easily pretty-print or clean-up the template preview and XML output?

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#17]
It can be difficult to format a twig template for readability, because it is a mix of twig logic and XML output, such that the resulting XML preview is also readable. I think it would be very helpful if the output and preview from a template could be cleaned up so the resulting XML is easier to read and to examine for potential errors.

**Comment by patdunlavey** [comment]
It's hard to optimize for both template readability and generated xml readability.

Have you looked at the {%spaceless%} tag? https://twig.sensiolabs.org/doc/2.x/tags/spaceless.html It will remove whitespace *between* tags, so the xml all runs together. But its output will be more readable.

Alternately, if you don't use spaceless, and format your template for readability, with line breaks and code indenting, you'll get a lot of extra space and linebreaks in your xml.

There may be a not-difficult way to make IMI's xml preview work one way and the actual xml generation work another, but that seems to run counter to the purpose of the preview!

**Comment by DiegoPino** [comment]
I have a XML format snippet somewhere around. It shows even some nice coloring. But  {%spaceless%} tag https://twig.sensiolabs.org/doc/2.x/tags/spaceless.html  as @patdunlavey suggested is also a very very very (very) good idea.

**Comment by McFateM** [comment]
I guess I was thinking more in terms of passing the XML preview, or the XML output itself, through something like xmllint or xml_pp as discussed, for example, in https://stackoverflow.com/questions/16090869/how-to-pretty-print-xml-from-the-command-line.

**Comment by DiegoPino** [comment]
This is fixed in https://github.com/mnylc/islandora_multi_importer/tree/googleAPI-WIP so closing. Extra blank lines are stripped and XML is "enriched" with pretty colors.
