### ISSUE TITLE
Add a special 'index' column so that sorting the spreadsheet is not problematic.

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#20]
I always add a simple import index or sort column to my data with a simple series of numbers within so that if the spreadsheet is ever sorted it can be restored easily. In the latest iterations of my process that index number is also saved since it is mapped into a mod extension field called /mods/extension/import_index. This way I can always easily tell from which row of the sheet an object was imported.  I have also considered adding an additional extension field called csv_path to store a persistent path to the CSV data file that a collection of objects was ingested from.  This way each imported object stores its own path or history leading back to the original data.

**Comment by McFateM** [comment]
If an 'index' column is introduced I think it would be nice to key the parent/child relationships based upon it rather than on row numbers.  Right now if someone sorts a sheet before ingest then all of the defined parent/child row relationships are in jeopardy since the children relate to their parent with a row number that is not necessarily 'permanent'.

**Comment by DiegoPino** [comment]
This one is very simple to implement (code) but requires some thinking about the UI we use to expose that option (and explain) to our users. Maybe we need an "advanced" tab?

**Comment by patdunlavey** [comment]
In terms of UI, it seems like it would be easy to make the checkbox in the "parent object" row in the object properties mapping form into a select list. Any thoughts on this wording?

If the value is not a well-formed PID, how should it be interpreted?
-  Ignored
-  As a persistent and unique value field identifying the parent row
-  As a row position identifier for the parent row in the csv

**Comment by McFateM** [comment]
Sorry it has taken me so long to get back to IMI work, but holding a PID in this column isn't really what I was looking for.  I'm advocating that it be used essentially as a replacement for row numbers, simply because row numbers change, relatively speaking, when you sort a worksheet.  And also because I like to capture the "index" value in a MODS/extension element so that I can easily look at an ingested object and determine exactly where it came from (I also ingest the path to the worksheet itself into a MODS/extension field).

As for UI concerns... I'd advocate just making certain worksheet column names/labels significant.  We already have CMODEL, SEQUENCE and others, why not just add an IMPORT_INDEX column?  If a column with this label exists, use it; if not, simply employ the logic which already exists.

Just my $0.02.  Thanks all.

**Comment by DiegoPino** [comment]
@McFateM ok. consider it done. Will merge a bunch of improvements this weekend, including that one. Will probably tune the UI part a bit. Thanks

**Comment by McFateM** [comment]
Sounds great Diego, and thank you.  FYI… I’m looking forward to getting back to some IMI work for the next week two or three weeks.  I’m pulling a code update today (and probably again next week) and might add another issue/enhancement just to see if others might be interested in reading/writing directly from Google Sheets without requiring an export to CSV.  Take care.

On Jun 29, 2017, at 2:05 PM, Diego Pino Navarro <notifications@github.com<mailto:notifications@github.com>> wrote:


@McFateM<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcfatem&d=DwMCaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=PQglHQe-EzyZqJOuOVcmU0OZ6bg-89msSPuqyNlQr28&m=9qpY4k903qaIzfGNZ-Q0sEwHJgt44xL8VhiofdQHJDA&s=9q1Yu6XMpj6ulj7bV17yp0d2lroQMPp1w0Cn7kq-34U&e=> ok. consider it done. Will merge a bunch of improvements this weekend, including that one. Will probably tune the UI part a bit. Thanks

**Comment by McFateM** [comment]
I'm planning to address this further in a PR today. My implementation in the case of Google Sheets is pretty simple, in islandora_multi_importer_read_googledata() in utilities.inc I added the following logic..

```
      // MAM. Append the $spreadsheetId and placeholder for the sheet row number (import_index) to the headers.  See issues #20 and #42
      $rowHeaders_utf8[] = 'import_source';
      if (!isset($rowHeaders_utf8['import_index'])) {
        $rowHeaders_utf8[] = 'import_index';
        $append_import_index = TRUE;
      } else {
        $append_import_index = FALSE;
      }

      foreach ($sp_data as $rowindex => $row) {
        // Google Spreadsheets start with Index 0. But PHPEXCEL, parent`s
        // function does with 1.
        // To keep both function responses in sync using the same params, i will compensate offsets here: 
          
          if (($rowindex >= 1) && ($rowindex > ($offset-1)) && (($rowindex <=($offset + $numrows)) || $numrows == -1 )) {
            $rowdata = array();
            // gets one row data
            
            $flat = trim(implode('', $row));
            //check for empty row...if found stop there.
            if (strlen($flat) == 0) {
              $maxRow = $rowindex;
              break;
            }

            if ($flat[0] != '#') {
              $row[] = $spreadsheetId;   // MAM. Append the $spreadsheetId to the end of the row as import_source  Issues #42
              if ($append_import_index) { $row[] = $rowindex; }  // MAM. Append the $rowindex to the end of the row as import_index  Issue #20
              $table[$rowindex] = $row;  // MAM. Partially addresses https://github.com/mnylc/islandora_multi_importer/issues/15
              $maxRow = $rowindex;
            }
          }
        }
    }

```

**Comment by DiegoPino** [comment]
@McFateM I wonder if you could write some nice Docs/workflow tutorials on that for other IMI users (please?). Sounds great(and makes me super happy) to see so many good and well-planed workarounds to make meta-existence easier =) IN specific about the pull, i really like your approach but i don't want to force people into a specific character/sintax that could actually mean something different for them and is actually hidden for new users, so the UI option/field people can select for the ordering seems more transparent for me. Your option/solution is quite good but will require accompanying documentation to make sure it does not become obscure functionality, so please keep that in mind. Thanks!

**Comment by McFateM** [comment]
I agree Diego, a UI option to select the ‘index’ column would be much better.  I’ve never been very good at implementing UI in Drupal but I’ll give it a try in the Object Properties form.

-Mark M


On Nov 2, 2017, at 10:13 AM, Diego Pino Navarro <notifications@github.com<mailto:notifications@github.com>> wrote:


@McFateM<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcfatem&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=PQglHQe-EzyZqJOuOVcmU0OZ6bg-89msSPuqyNlQr28&m=qHWJeML4D7AwctY9zmbv2nEJSQXFU_06tn7QfknqDMk&s=1IbbPH39L7Huyw60HlGS0dRQrDwX_C8qJ5E8w2_6lp0&e=> I wonder if you could write some nice Docs/workflow tutorials on that for other IMI users (please?). Sounds great(and makes me super happy) to see so many good and well-planed workarounds to make meta-existence easier =) IN specific about the pull, i really like your approach but i don't want to force people into a specific character/sintax that could actually mean something different for them and is actually hidden for new users, so the UI option/field people can select for the ordering seems more transparent for me. Your option/solution is quite good but will require accompanying documentation to make sure it does not become obscure functionality, so please keep that in mind. Thanks!

**Comment by McFateM** [comment]
I am now having second thoughts about introducing a UI option for this. I am honestly not sure how to implement it in the UI because the logical place for it would be in the properties form so that the user could select a column, or None, from the headers that have been gleaned from the spreadsheet. However, that portion of the UI isn’t connected until after the spreadsheet pre-process has taken place.

And effective use of this feature depends on the twig template that you are using as well.  So I think it remains a “special” feature no matter what we do with it.

Perhaps this is another item we could discuss in a phone call?

Sent from my iPad

On Nov 2, 2017, at 10:13 AM, Diego Pino Navarro <notifications@github.com<mailto:notifications@github.com>> wrote:


@McFateM<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcfatem&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=PQglHQe-EzyZqJOuOVcmU0OZ6bg-89msSPuqyNlQr28&m=qHWJeML4D7AwctY9zmbv2nEJSQXFU_06tn7QfknqDMk&s=1IbbPH39L7Huyw60HlGS0dRQrDwX_C8qJ5E8w2_6lp0&e=> I wonder if you could write some nice Docs/workflow tutorials on that for other IMI users (please?). Sounds great(and makes me super happy) to see so many good and well-planed workarounds to make meta-existence easier =) IN specific about the pull, i really like your approach but i don't want to force people into a specific character/sintax that could actually mean something different for them and is actually hidden for new users, so the UI option/field people can select for the ordering seems more transparent for me. Your option/solution is quite good but will require accompanying documentation to make sure it does not become obscure functionality, so please keep that in mind. Thanks!

**Comment by DiegoPino** [comment]
yeah, lets plan for a call. Let me think about this, i see some options but my brain is burned already today. Next week?
Diego Pino Navarro
Metropolitan New York Library Council
599 11th Av. New York, NY 10036

**Comment by McFateM** [comment]
Yes.  I’m going to leave my UI changes in the code so you can see where I was going with this, but that new UI element won’t have any real impact yet.

I’m on campus next Monday morning and all day Tuesday.

On Nov 2, 2017, at 2:30 PM, Diego Pino Navarro <notifications@github.com<mailto:notifications@github.com>> wrote:

yeah, lets plan for a call. Let me think about this, i see some options but my brain is burned already today. Next week?
Diego Pino Navarro
Metropolitan New York Library Council
599 11th Av. New York, NY 10036

**Comment by McFateM** [comment]
@DiegoPino  After our discussion today I think I have found a better way to preserve our workflow without requiring any changes to any data.  The solution will provide a text control in the UI allowing the user to disable this feature, or specify an optional string of text to be appended to each row of imported data as a column named 'imi_import_source' (I choose this column name/header assuming nobody is likely to include the same in their data, and will document it).  For Google Sheets the UI default for this control will contain the ID of the imported Google Sheet followed by the user-specified import range.  When a row of data is ingested the feature, if enabled, will append the worksheet row number to the text, and subsequently append that result to the data.

**Comment by McFateM** [comment]
It is likely that Grinnell College will still maintain the 'import_index' column that we like to introduce to overcome sorting issues, but we will no longer ingest it.  Instead we will ingest, using this feature, the row number of each record and simply use the 'import_index' column in our workflow to re-sort the worksheet, if necessary, to make the recorded row numbers meaningful and accurate.

I think this will work nicely in conjunction wth the practice of keeping a "Master" tab/sheet in each Google Sheet while importing from copies of that tab in order to control which rows are read and which are not.  I'll try to work up some documentation with examples of this workflow in use.

**Comment by McFateM** [comment]
Closing this issue as I believe it is better address in my workflow, especially with the "tracking" feature I'm adding for Google Sheet users.
