### ISSUE TITLE
Add a simple post-processing hook for each object ingested.

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#21]
I have a few scripts that I like to run on newly ingested objects and having a hook that fires after each object is ingested would be a nice addition.

**Comment by patdunlavey** [comment]
There is already a hook that fires during batch ingest: https://github.com/Islandora/islandora_batch/blob/7.x/islandora_batch.api.php. 

Does that not meet your need @McFateM ?

**Comment by McFateM** [comment]
Yes, I think that could be used.  Thanks for identifying that Pat.

-Mark M.

On May 22, 2017, at 8:07 PM, Pat Dunlavey <notifications@github.com<mailto:notifications@github.com>> wrote:


There is already a hook that fires during batch ingest: https://github.com/Islandora/islandora_batch/blob/7.x/islandora_batch.api.php<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Islandora_islandora-5Fbatch_blob_7.x_islandora-5Fbatch.api.php&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=PQglHQe-EzyZqJOuOVcmU0OZ6bg-89msSPuqyNlQr28&m=A-i9vNJSqAshD0SD3jZftOmmRrTfodgZMCiQWWQzldQ&s=ge_qKXth0qz4eJxfWB4TIZtZtciEmYIE1IGG_bvApe4&e=>.

Does that not meet your need @McFateM<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcfatem&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=PQglHQe-EzyZqJOuOVcmU0OZ6bg-89msSPuqyNlQr28&m=A-i9vNJSqAshD0SD3jZftOmmRrTfodgZMCiQWWQzldQ&s=_9zrPdF7m8ZrPLwTqUhX5R5gYsJfVkLmFMI2ExiY8-w&e=> ?

**Comment by patdunlavey** [comment]
Great. @DiegoPino, can you close?

**Comment by DiegoPino** [comment]
Closing it. Thanks to both!
