### ISSUE TITLE
Save and load Twig templates to/from files.

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#24]
Add the ability to save and load Twig templates from files without having to copy and paste. This would make it easier to build and share a repository of templates.

**Comment by DiegoPino** [comment]
Suggestion: shamelessly copy the islandora XML forms admin interface and put my saving class in place for that. We need basically the same. I have something like that but would prefer if you give this a try

**Comment by DiegoPino** [comment]
@McFateM @patdunlavey so the class is https://github.com/mnylc/islandora_multi_importer/blob/master/includes/TwigTemplateDatabase.inc
used/implemented here (save, list, etc)

https://github.com/mnylc/islandora_multi_importer/blob/41f09191096489fe89062c0c0e471b8d29bed78e/includes/utilities.inc#L141-L163

Which is pretty much the same that is used here
https://github.com/Islandora/islandora_xml_forms/tree/57b26d5f24fec0111ecda554f11865b5f71e50c3/builder

The shameless copy means use what is good, rethink what is wrong. the XML forms builder admin interface is good but lacks a lot. Forms are identified by their labels and not unique IDS. We don't keep track of when the last time a form was modified and by whom, etc. I could go on and on the whole day.
But: the form that lists and allows you to import, save, copy and delete seems to be good enough for this issue

**Comment by DiegoPino** [comment]
I did not see any progress from you folks on this, so this became part of https://github.com/mnylc/islandora_multi_importer/tree/googleAPI-WIP now. Closing
