### ISSUE TITLE
googleAPI-WIP - ingest error

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#27]
Clicking to ingest after going through the wizard produces the following error:

```
    Notice: Undefined variable: file in islandora_multi_importer_form_submit() (line 1137 of /var/www/drupal/sites/all/modules/islandora_multi_importer/includes/import.form.inc).
    Recoverable fatal error: Argument 1 passed to file_usage_add() must be an instance of stdClass, null given, called in /var/www/drupal/sites/all/modules/islandora_multi_importer/includes/import.form.inc on line 1137 and defined in file_usage_add() (line 688 of /var/www/drupal/includes/file.inc).
```

I have a slightly older vagrant.  Will try to reproduce this issue with the latest 1.9 machine.

**Comment by DiegoPino** [comment]
@Natkeeran looking at this. This is part of the "download your google spreadsheet data to a file prior ingest" approach I added yesterday. maybe something is missing...

**Comment by Natkeeran** [comment]
I used a CSV for this.

**Comment by DiegoPino** [comment]
@Natkeeran ok got.  Solved via https://github.com/mnylc/islandora_multi_importer/commit/b777fc95338f663cfedeb3471678b669eb9b3245

**Comment by Natkeeran** [comment]
@DiegoPino Seems good.  Thank you.

**Comment by DiegoPino** [comment]
Cool, closing as fixed! Thanks @Natkeeran
