### ISSUE TITLE
Unable to add New Twig template after fresh install from menu

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#28]
## Steps to Reproduce
* Do a fresh install of the googleAPI-WIP branch
* Go to http://localhost:8000/admin/islandora/twigtemplates
* Click New Twig template

## The expected behavior.
* Should allow the user to create/upload a twig template

## The actual, incorrect behavior.
Produces the following error:
```
    Notice: Undefined index: twig in islandora_multi_importer_twigcreateinternals_form() (line 127 of /var/www/drupal/sites/all/modules/islandora_multi_importer/includes/twig.manage.inc).
    Twig_Error_Loader: Template "__string_template__da09f6ff0d51999b81f1875452180375f675192db1b1cd2727bd21c24461acce" is not defined. in Twig_Loader_Chain->getCacheKey() (line 139 of /var/www/drupal/sites/all/modules/islandora_multi_importer/vendor/twig/twig/lib/Twig/Loader/Chain.php).

```

**Comment by DiegoPino** [comment]
@Natkeeran Ok, this one will go with other 2 other extra functions/improvements i was working on. So will take me 30 minutes more. Thanks for reporting

**Comment by DiegoPino** [comment]
Fixed via https://github.com/mnylc/islandora_multi_importer/commit/1efe044595823d80c5647298c2fd64a068b8374d
