### ISSUE TITLE
Unable to do CModel Mapping when islandora_compound_object module is enabled 

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#29]
## Steps to Reproduce
* Do a fresh install of the googleAPI-WIP branch
* Choose a data source (i.e csv)
* Choose a template and preview
* Go to CMODEL Mapping tab and choose the column of the CMODEL, and click the Check CMODELs button

## The expected behavior.
* Should allow the user to define the 
* Should show the Datastream IDS table configuration options to create them

## The actual, incorrect behavior.
Produces the following error:
```
An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /system/ajax
StatusText: n/a
ResponseText: 
Skip to main content
islandora-development.org
Error        The website encountered an unexpected error. Please try again later.                  
Error message
Recoverable fatal error: Argument 1 passed to islandora_compound_object_islandora_derivative() must be an instance of AbstractObject, none given in islandora_compound_object_islandora_derivative() (line 292 of /var/www/drupal/sites/all/modules/islandora_solution_pack_compound/islandora_compound_object.module).

ReadyState: undefined
```

## Note 
Disabling the compound module removes this error.  Can possibly be an issue in the compound object module!

**Comment by DiegoPino** [comment]
@Natkeeran that one is weird and new. Can't confirm here (release VM) and have islandora_compound_object module enabled. More over, i made a pull request that got merged on last release for that (wrong  but also i'm passing a fake object to avoid that in case some module has a wrong function signature). I just saw this one
https://github.com/Islandora/islandora_solution_pack_compound/pull/126/files
Could it be that?

**Comment by DiegoPino** [comment]
@Natkeeran see https://github.com/Islandora/islandora_solution_pack_compound/pull/126#pullrequestreview-55605618

**Comment by DiegoPino** [comment]
@Natkeeran opened a JIRA for this https://jira.duraspace.org/browse/ISLANDORA-2040

**Comment by Natkeeran** [comment]
@DiegoPino I do have the latest vagrant.

**Comment by DiegoPino** [comment]
@Natkeeran yes you do, that breaking change is from July, vagrant gets 7.x. I was running 7.x-1.9. 
This fixes it (please test)
https://github.com/mnylc/islandora_multi_importer/commit/b912fcf09e331ef9604ceaab5c96c58a19afeee8 and 
https://github.com/mnylc/islandora_multi_importer/commit/99a6ae4d0f41ef257b841083c7ec4f2f778469d2
Introduce a workaround using my ```fakeobject class```.  I would love to remove that in the future but seems like people use hooks more liberally was I was guessing.

**Comment by Natkeeran** [comment]
Yes, the fix looks good.

**Comment by DiegoPino** [comment]
Ok, will close. thanks for testing. No time during Committers call today to review my JIRA ticket
