### ISSUE TITLE
Google sheet - MODS Preview - Template parsed output is not generated

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#31]
## Steps to Reproduce
* Do a fresh install of the googleAPI-WIP branch or git pull and composer update
* Configure the Google API 
* Go to http://localhost:8000/multi_importer
* In the data selection section, choose Google Spreadsheet URL
* Provide the ID, Sheet name and range (Make sure to provide the correct sheet name)
* Click to preprocess
* The data from the google spreadsheet should be visible in the "Preview submited file data values" accordion 
* Chose a row
* Click the Template tab
* Choose or provide a template
* Click the Preview button

## The expected behavior.
* The preview should generate the MODS xml with the selected row's data

## The actual, incorrect behavior.
* The preview only produces an empty MODS skeleton 

## Note 
* If you ingest, it does create the MODS with values from the google spreadsheet.  It is an issue with the preview.

**Comment by DiegoPino** [comment]
@Natkeeran. Google spreadsheets is case sensitive for its headers. Could it be that? Tested with:
https://docs.google.com/spreadsheets/d/1uWAckOCDbfsxZLiVzd1px3ojeN6vC__zER-hIe0o5YE/edit#gid=0
and this Template:
https://gist.github.com/DiegoPino/9dc4382e72d1658dbc920c94c004db0a
Result, same as you got, empty skeleton based on template.

Went and replaced in the template (twig) data.title for data.Title. Title appeared in the preview.
Which makes me wonder why it worked out on the import itself... maybe i'm doing some sanitation afterwards, but can't remember where.

Can you confirm MODS files where correctly generated in drupal's file system? Can you confirm that if the header names match, you get an results? does it matter which row you select?

**Comment by Natkeeran** [comment]
@DiegoPino I tried it with the spreadsheet and template you provided.  Data loads, but the preview does not get generated.

**Comment by DiegoPino** [comment]
@Natkeeran weird, can´t reproduce. Will start from fresh. i can see the preview.

**Comment by DiegoPino** [comment]
@Natkeeran tried a few times with different combinations and I still get a correct Preview. The only issue is the lower case v/s uppercase of the headers. But if you correct that (which is not an error) then it works. Can you re-test when you have some time?

I also did a composer update/install and even recreated the templates. Maybe there is some cache in place? Any Javascript issue? Not sure what can differ in our setups but this has me clueless.

Thanks a lot

**Comment by Natkeeran** [comment]
Hi @DiegoPino 

I've rested it with latest pull and composer update.  Seems good.  

I did test it with the csv and template you suggested, that is why I did not think it was casing issue.  It is possible I missed something.  Looks good.  Please do let me know when the update stuff is in, will give it a go.  Thank you.

**Comment by DiegoPino** [comment]
@Natkeeran you got the full set of emoticons. Thanks! Ok, will continue. Added a few things that solved a few of your open issues. Keep them coming.
 Need to deal with a separate batch interface (not the UI anymore) for the Update data stream issue. Probably will create a few new batch states to deal with the exception. 
Should be done by tomorrow. Thanks for testing.
