### ISSUE TITLE
Google Sheet header/column names not converted to lowercase

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#43]
In the GoogleAPI-Update-WIP branch of the code I found that headers/column names were not being converted to lowercase as they are in the case of CSV file import.  This issue should be resolved in a PR I hope submit later today.

**Comment by DiegoPino** [comment]
@McFateM true but my approach is different.  Maybe, the issue is with CSV/Excel library and keeping/using the correct case is something we should expect/accept?

**Comment by McFateM** [comment]
This was resolved shortly after I bumped into it, and remains resolved in the latest PR.
