### ISSUE TITLE
Allow user to provide full URL of Google Sheet in place of the sheet "ID"

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#44]
Reading directly from Google Sheets is a tremendous improvement!  But I had issues with typos when pasting a sheet ID into the input form.  So I propose, and have made, a change that will allow a user to input the entire Google Sheet URL.  The code then parses the ID portion from the URL.

**Comment by DiegoPino** [comment]
@McFateM can be done. I was just afraid that URL can change (in form) quite a bit, so not sure which nomenclature to take as reference. I see a lot of changes being made by you. Are you actually making /various pull request? I'm hoping so. (smile)

**Comment by McFateM** [comment]
Yes, I’m adding issues that I have address in my code and will submit that in a PR, hopefully yet this morning.   My plan for the PR is to sync DigitalGrinnell/islandora_multi_importer with your GoogleAPI-Update-WIP code and then pull against that branch.  Wish me luck.

**Comment by DiegoPino** [comment]
merci!

**Comment by McFateM** [comment]
This issue seems to have been nicely addressed in "master" already.  I'm going to mark this Closed.  Thanks.

**Comment by DiegoPino** [comment]
@McFateM thanks to you. It is your beautiful code!
