### ISSUE TITLE
Spreadsheet returns NO data...issue warning and return to form

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#45]
I've encountered cases with Google Sheets where my specified "range" returns NO data.  In such an instance the system throws lots of subsequent errors if left as-is.  So I've added a bit of code that traps this condition, issues a warning, and leaves the user in the data selection input form.

**Comment by DiegoPino** [comment]
nice.

**Comment by McFateM** [comment]
Will be offering this in a new PR.  Code in utilities.inc, lines 187-192 is...

`  // If the $range returns no data...let the user know and leave them in the current screen.
  if ($maxRow === 0) {
    $msg = "Retrieve of Google Sheet '$spreadsheetId' and range '$range' returned NO active data.";
    drupal_set_message($msg, 'warning');
    drupal_goto('/multi_importer');
  }
`

**Comment by DiegoPino** [comment]
Fixed in Master. Thanks @McFateM
