### ISSUE TITLE
Error throwing in FedoraRelationships->getDom()

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#54]
I am using googleAPI-Update-WIP branch with 7c7aae7fa9043eddc013e2b51fe87befc37569c0 commit in our pre-prod environment.  I am running into an issue that I did not see in the vagrant (using the same csv, twig and zip (no objects).

When processing the object, it seems to ingest the first object.  Flow comes to here: https://github.com/mnylc/islandora_multi_importer/blob/googleAPI-Update-WIP/includes/islandora_multi_batch.inc#L454.  All subsequent objects do not get ingested.  

Then it errors out with the following messages in the watchdog:
```
Error: Call to a member function setAttribute() on null in FedoraRelationships->getDom() (line 243 of /var/www/gundagunde/sites/all/libraries/tuque/FedoraRelationships.php).

Warning: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in 
FedoraRelationships->getDom()
```

No additional log in apache.  Not sure where exactly it gets thrown.

**Comment by DiegoPino** [comment]
Hi Nat, can you (privately if needed) share your ingest/update data? Seems like it is trying to add a RELS-EXT (or int?) relationship on a non existing or wrongly formed RDF datastream. If updating, can you share the RELS-EXT/INT DS of the object that fails? Never seen that error before!

**Comment by Natkeeran** [comment]
Hi @DiegoPino 

For the first object, which gets marked as successfully ingested, it creates the RDF as expected.  If I process the batch again, it will ingest the second object.  Note that I cannot reproduce this issue in the vagrant, only in the pre prod.  There, we have the needed islandora_batch and multi importer versions.  
 
[GG_MODS.twig.txt](https://github.com/mnylc/islandora_multi_importer/files/1623581/GG_MODS.twig.txt)
[testdata.csv.txt](https://github.com/mnylc/islandora_multi_importer/files/1623582/testdata.csv.txt)

**Comment by DiegoPino** [comment]
@Natkeeran seems like an issue with Tuque and it's commit strategy if RELS-* DS exists/not. Can you try to update tuque to 1.10 in the meanwhile on that test machine and see if you can reproduce the error? I will dig into your data and see if I can find any issues

**Comment by Natkeeran** [comment]
@DiegoPino I initially thought Tuque might be an issue, and both machines have the latest.  I cannot reproduce it the vagrant.

**Comment by DiegoPino** [comment]
Ok, will investigate! Thanks a lot. Give me 24 hrs (i could need a reminder!)

**Comment by Natkeeran** [comment]
Thank you.  I have the same islandora, islandora_solution_pack_boo, islandora_book_batch, tuque, islandora_batch and islandora_multi_importer in both environments.  Let me know if there is some avenue that I should look into.

**Comment by DiegoPino** [comment]
Hi Nat,

I tried to replicate the issue without luck. Are there any other outstanding differences between your both repositories? You are doing an ingest (new objects) right?

The error you are seeing is extremely strange. On the tuque side, the DOM document (from RELS-EXT)  is NULL in your failed case. 

"documentElement
This is a convenience attribute that allows direct access to the child node that is the document element of the document."
https://github.com/Islandora/tuque/blob/1.10/FedoraRelationships.php#L240-L244

That should only happen if this here fails to be smart

https://github.com/Islandora/tuque/blob/1.10/FedoraRelationships.php#L224-L237
Means, the cache exists but is null! In any other case Dom will have a root element and should work (i guess!)

So, on the multi importer side, sadly most of the RELS ext is pretty manual since solution packs dont provide hooks or info functions to get those from them but you could actually put some debug statements inbetween

https://github.com/mnylc/islandora_multi_importer/blob/googleAPI-Update-WIP/includes/islandora_multi_batch.inc#L835-L954

And see what is wrong.
Also checking where / how tuque fails there can help. 
Any other special settings? I'm clueless really

Let me know and feel free to write me directly if needed
Best

**Comment by Natkeeran** [comment]
Hi @DiegoPino 

I did some troubleshooting.  Here is what I found.

The failure occurs on the item being ingested.
Here, it expects an xml string https://github.com/Islandora/tuque/blob/1.x/FedoraRelationships.php#L228, and instead it gets the following: uploaded://471.  

If I handle that case as below, the ingest processes without issues:
```
if (strpos($this->datastream->content, 'upload') !== false) {
      $document = new DomDocument("1.0", "UTF-8");
      $rootelement = $document->createElement('rdf:RDF');
      $document->appendChild($rootelement);
}
```

The stack trace of functions:
```
getDom, internalGet, get, islandora_batch_report_islandora_batch_object_processed, module_invoke_all, islandora_batch_process_results, islandora_batch_ingest_process, _batch_process, _batch_do, _batch_page, system_batch_page, menu_execute_active_handler
```
[sample_stack_tract.txt](https://github.com/mnylc/islandora_multi_importer/files/1640483/sample_stack_tract.txt)

I've also attached a sample full stack trace.

We might not encounter this in prod, since we will only be updating.  This might be because, islandora book batch ingest expects an OBJ object.

**Comment by DiegoPino** [comment]
HU!!! uploaded://471!! That is the drupal handle, weird!! OK. That can help me to find the issue. Did you try doing this with caching disabled?

**Comment by DiegoPino** [comment]
@Natkeeran why is nonMagicAutoCommit=> 1 ???

**Comment by Natkeeran** [comment]
@DiegoPino Yes caching is fully turned off.  Not sure what nonMagicAutoCommit flag represents.

**Comment by DiegoPino** [comment]
Hi Nat, would it be possible to ask Irfan/you for a list of enabled drupal modules, not regular stack info( like you are using a special version of tomcat) and lastly your PHP version?
Working hard on this!

**Comment by Natkeeran** [comment]
Hi Diego, I've sent this info.  Thank you.  It does not seem to know how this error impacts the ingest/update processes.  When I put in the work around, the ingested objects seem good.

**Comment by DiegoPino** [comment]
@Natkeeran yeah... but that workaround is so exceptional and i actually need (HELP!) to understand the reason.. if you write the following in a PHP Devel block

print_r(stream_get_wrappers());

What do you get? 


I'm very curious about the **uploaded://471** and how that one gets created (multi importer does not do that), the uploaded:// is to my knowledge no standard stream wrapper in php and RELS-EXT is actually created directly by tuque/fedora, not by us normally. This is my output, in 3 of our machines, 
So actually what is happening there is that when tuque asks fedora/or drupal *can't be sure there! for the datastream, someone is adding stuff to the emptyness...unexistince of that datastream and that string, uploaded://471 is not standard PHP..

Ok, my output is this
Array
(
    [0] => https
    [1] => ftps
    [2] => compress.zlib
    [3] => php
    [4] => file
    [5] => glob
    [6] => data
    [7] => http
    [8] => ftp
    [9] => compress.bzip2
    [10] => phar
    [11] => zip
    [12] => public
    [13] => temporary
)


I have many different versions, but 2 of them running PHP 7 (production compiled version, not debug PHP by the way), and we have some machines with tomcat 7 and tomcat 8 running. I wonder if some other piece of software is interfering with the way tuque creates RELS-EXT...

**Comment by DiegoPino** [comment]
And @Natkeeran finally (sorry), any chance Irfan enabled
[Tuque]
tuque.rels_ds_control_group = M 

?

**Comment by Natkeeran** [comment]
Yes, that option is enabled.

print_r(stream_get_wrappers()); output is as below:
```
sArray ( 
[0] => https 
[1] => ftps 
[2] => compress.zlib 
[3] => php 
[4] => file 
[5] => glob 
[6] => data 
[7] => http 
[8] => ftp 
[9] => phar 
[10] => zip 
[11] => public 
[12] => temporary 
[13] => private ) 
```

**Comment by adam-vessey** [comment]
Just a couple of cents: Tuque uploads managed files before assembling the FOXML which gets ingested into Fedora when ingesting objects, using URIs to point to the uploaded files... IIRC, these URIs have that same `uploaded://number` format.

**Comment by Natkeeran** [comment]
Essentially, the solution is to not to use tuque.rels_ds_control_group = M option.  You can comment that out in php.ini if you have enabled it.  Does not seem to be islandora_multi_importer issue.  

Created a JIRA ticket to followup this issue: https://jira.duraspace.org/browse/ISLANDORA-2150
