### ISSUE TITLE
Update - Do not create derivative option

### ISSUE THREAD

**Issue by Natkeeran** [mnylc/islandora_multi_importer#56]
For a large image, multi_importer provides an option to not to create OBJ.  However, it does not provide option to not to create the derivatives.  Not sure if it actually re-generates the derivatives.

**Comment by DiegoPino** [comment]
@Natkeeran on "Update", never thought about it. Options are:
1.- Flag the object to bypass derivatives? (RELS-EXT)
2.-Oposite, force RUN derivative regeneration

Most derivatives won't run if the destination DS already exists and not being forced (normal DS update) but that depends on each piece of code that runs it. Do you want me to investigate?

**Comment by Natkeeran** [comment]
@DiegoPino 

No need to investigate it at this time.  It does not seem to regenerate it for large images.  Not an issue for us right now.  Thank you.
