### ISSUE TITLE
Workflow/Suggestions for Ingesting a Book via IMI?

### ISSUE THREAD

**Issue by McFateM** [mnylc/islandora_multi_importer#66]
Can anyone suggest how one might ingest a book via IMI?  I anticipate having some multi-page PDFs that we'd like to create IA book objects from.  Can it be done with IMI?  Should it be done via IMI?  If yes, how do you specify the spreadsheet data for a book?

**Comment by DiegoPino** [comment]
Will get back to you tomorrow on this. We have a workflow I can share that works well for us. 27000 pages in a week.

**Comment by petermacdonald** [comment]
I just tried ingesting a 3-page manuscript object using bookCModel, but IMI errors out on the first first object. The IMI doesn't ask for me to configure the bookCmodel in any IMI dialog box. The IMI module sets up my book as a compound object, but barfs on the main object. I guess I need to wait for the workflow suggestions for ingesting a book that you mentioned earlier, Diego. BTW. I can ingest compound objects just fine, but I'd like to ingest as a book.

**Comment by DiegoPino** [comment]
@petermacdonald you probably have the CMODELs wrong, we ingest books all the time.

Check this spreadsheet out, has the most common CMODELS and i can say for sure it works 

https://docs.google.com/spreadsheets/d/1v1bkNP_4HYx-ICANNRrirS8hX_3aT2TECeRS-xK2q8g/edit?usp=sharing

**Comment by DiegoPino** [comment]
The PID column is not needed of course, but can be used to update objects later if you need to.

**Comment by McFateM** [comment]
And be careful with capitalization in the CModel column too!   I ran into a bunch of errors with islandora:CompoundCModel, because of that first capital 'C'.

**Comment by McFateM** [comment]
You are welcome, sir.  

And just FYI... I'm hoping to write an IMI-compatible CSV export module this summer, one that exports a CSV file from existing records in a format that can be edited and quickly re-ingested.  Along with that I hope to include a feature to do a consistency check of any CSV against a specified TWIG template, and also catch things like obvious CModel spelling errors and unwanted characters.

But, Peter, you'll have to stick around longer than July in order to reap any benefits from this work.  8^)

**Comment by McFateM** [comment]
OK, I have a working, albeit slow, solution now.  The process takes advantage of hook_islandora_batch_object_processed.

My implementation of this hook looks like this:

https://github.com/DigitalGrinnell/dg7/blob/f5aad0a2f8f980bca3a66fac069d49e4a235a0ff/dg7.module#L2312

It's not pretty, yet.  It has quite a few hard-coded assumptions, but they all work for me. It could stand to do more checking and error reporting, but it works.  That's what hook implementations are supposed to do, right?

I'll try to clean it up a bit in the next week or so.  Until then, I have a half-dozen more books (1000 pages?) to ingest!

**Comment by DiegoPino** [comment]
@McFateM closing since #73 was merged. Feel free to reopen if this requires more work!
