### ISSUE TITLE
Deleting unused Twig Templates

### ISSUE THREAD

**Issue by petermacdonald** [mnylc/islandora_multi_importer#67]
How does one delete unused Twig Templates? Trial and error during configuration of my MODS template has left a lot of obsolete versions of the template behind.

**Comment by petermacdonald** [comment]
Thanks, DIego.

I didn't have the "Multi Importer Twig templates" menu in admin/islandora, so I checked Permissions for the module.

I found that the permission box next to "Manage Islandora Multi Importer Twig templates" was not checked. Once I gave myself the permission, I was all set.

Thanks again.

**Comment by DiegoPino** [comment]
Closing as solved
