### ISSUE TITLE
Give the user a message/data after ingesting to batch preprocessor

### ISSUE THREAD

**Issue by DiegoPino** [mnylc/islandora_multi_importer#7]
For debugging purposes, after sending a multi importer set to batch preprocessor we return to the last form (zip upload or step 2 depending on what the user selected). We should redirect to a message page which gives the user a link to the batch set, the number of processed objects, etc and a downloadable spreadsheet containing for example the final PID that will be created for each data row that was submitted

**Comment by patdunlavey** [comment]
Let's review this ticket in light of recent work pushed out by @DiegoPino.

**Comment by DiegoPino** [comment]
Please give this a test. Not sure if the message is explicit, good enough. If it is (crossing fingers) we could close this issue.

**Comment by DiegoPino** [comment]
This one is done. Closing
