### ISSUE TITLE
Has un-declared dependency on field_group

### ISSUE THREAD

**Issue by whikloj** [mnylc/islandora_multi_importer#8]
Needs [field_group](https://www.drupal.org/project/field_group) added to the *.info file as a dependency.

https://github.com/mnylc/islandora_multi_importer/blob/master/includes/import.form.inc#L332
https://github.com/mnylc/islandora_multi_importer/blob/master/includes/import.form.inc#L335

**Comment by DiegoPino** [comment]
@whikloj true, forgot to tell you that and to include it, will fix it. thanks!

**Comment by DiegoPino** [comment]
Was fixed a few months ago, forgot to update!
