### ISSUE TITLE
Error processing batch set after ingest through multi-importer

### ISSUE THREAD

**Issue by ChrisStanton** [mnylc/islandora_multi_importer#9]
Error in batch ingest in set 70 on dev.dcmny.org:

http://dev.dcmny.org/multi_importer#overlay=admin/reports/islandora_batch_queue/70

Stuck on the following screenshot for a long time, after starting "processing" set:

<img width="1214" alt="screen shot 2016-09-20 at 4 51 25 pm" src="https://cloud.githubusercontent.com/assets/8247616/18688475/90ee0ce2-7f52-11e6-81d8-4f5040829880.png">

Then get the following error:

<img width="1213" alt="screen shot 2016-09-20 at 5 14 57 pm" src="https://cloud.githubusercontent.com/assets/8247616/18689161/cb992f40-7f55-11e6-9dfa-b285e8c3dcb9.png">

CSV and zip I used for testing through multi-importer are in this zip:

[armbruster_test.zip](https://github.com/mnylc/islandora_multi_importer/files/483582/armbruster_test.zip)

**Comment by DiegoPino** [comment]
@ChrisStanton

**Comment by DiegoPino** [comment]
to document this:

- To  escape XML tag values use escape('html')
- To escape XML tag properties use escape('html_attr')

Now working on a few security features to avoid this in the future:
 1. If resulting document from twig template is not an valid XML, use a stub XML, add the object to an "failed" report list.
2. Fix metrodora so infinite loops never ever happen again
3. Add a test XML validity button in the Twig preview page
4. Add a "dry run" button before ingesting to test all rows on an Spreedsheet

**Comment by DiegoPino** [comment]
Fixed. Won't loop again!. Will open a new one for "dry run"
