### ISSUE TITLE
Give Datastreams their original file name as a label

### ISSUE THREAD

**Issue by DiegoPino** [mnylc/islandora_multi_importer#99]
As reported here https://groups.google.com/d/msg/islandora/GcBZt12u12o/LaEAXMazAAAJ
People would like to use the filename as a label for a datastream. This would only apply for Source Files (like OBJ). Mark Sandford and Amy Blau help is coming!

**Comment by dnwk** [comment]
+1 heart

**Comment by dnwk** [comment]
+1

**Comment by DiegoPino** [comment]
@dnwk merged into master. Please feel free to git pull. Closing as solved but can be reopened if my code does not work as intended. Solved via #100
